import jsPDF from "jspdf";

/**
 * Generates a professional, semantic PDF using native jsPDF commands.
 * This method creates ultra-lightweight files (approx 30KB) that easily fit in Firestore.
 */
export const generateSemanticPDF = async (reportData, meta) => {
    const { departmentName, submittedBy, userEmail, date } = meta;
    
    // Create PDF (Standard A4)
    const doc = new jsPDF({
        orientation: "p",
        unit: "mm",
        format: "a4",
        compress: true
    });

    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const contentWidth = pageWidth - (margin * 2);
    let currentY = 20;

    // --- HELPER: Handle Page Breaks ---
    const checkPageBreak = (neededHeight) => {
        if (currentY + neededHeight > 275) {
            doc.addPage();
            currentY = 20;
            drawFooter();
            return true;
        }
        return false;
    };

    const drawFooter = () => {
        const pageCount = doc.internal.getNumberOfPages();
        doc.setFont("helvetica", "italic");
        doc.setFontSize(9);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated by InstiReport Portal | Page ${pageCount}`, pageWidth / 2, 285, { align: "center" });
    };

    // --- DRAW HEADER ---
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(26, 54, 93); // Dark blue
    doc.text("MADHAV INSTITUTE OF TECHNOLOGY & SCIENCE, GWALIOR", pageWidth / 2, currentY, { align: "center" });
    
    currentY += 8;
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text("DEEMED TO BE UNIVERSITY | NAAC ACCREDITED WITH A++ GRADE", pageWidth / 2, currentY, { align: "center" });
    
    currentY += 15;
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, currentY, pageWidth - margin, currentY);
    
    currentY += 15;
    doc.setFontSize(22);
    doc.setTextColor(0, 0, 0);
    doc.text("ANNUAL DEPARTMENTAL REPORT", pageWidth / 2, currentY, { align: "center" });
    
    currentY += 10;
    doc.setFontSize(16);
    doc.setTextColor(59, 130, 246); // Accent blue
    doc.text(departmentName.toUpperCase(), pageWidth / 2, currentY, { align: "center" });
    
    currentY += 15;
    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    doc.text(`Submitted By: ${submittedBy}`, margin, currentY);
    doc.text(`Date: ${date}`, pageWidth - margin, currentY, { align: "right" });
    
    currentY += 6;
    doc.text(`Email: ${userEmail}`, margin, currentY);
    
    currentY += 15;
    doc.setDrawColor(59, 130, 246);
    doc.setLineWidth(0.5);
    doc.line(margin, currentY, pageWidth - margin, currentY);
    
    currentY += 15;

    // --- DRAW SECTIONS ---
    const sections = Object.keys(reportData).sort();
    
    sections.forEach((sectionTitle) => {
        const content = reportData[sectionTitle] || "No content provided for this section.";
        
        // Section Title
        checkPageBreak(25);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.setTextColor(26, 54, 93);
        doc.text(sectionTitle, margin, currentY);
        
        currentY += 8;
        
        // Section Content (Word Wrap)
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        doc.setTextColor(50, 50, 50);
        
        const lines = doc.splitTextToSize(content, contentWidth);
        const lineHeight = 6;
        
        lines.forEach(line => {
            checkPageBreak(lineHeight);
            doc.text(line, margin, currentY);
            currentY += lineHeight;
        });
        
        currentY += 10; // Space between sections
    });

    drawFooter();
    return doc;
};
