

import React, { useState, useRef } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import styles from './ReportStructurePageCSE.module.css';

const AccordionItem = ({ title, content, onContentChange }) => {
    const [isOpen, setIsOpen] = useState(false);
    return (
        <div className={styles.accordionItem}>
            <button className={styles.accordionHeader} onClick={() => setIsOpen(!isOpen)}>
                <span>{title}</span>
                <span className={`${styles.accordionIcon} ${isOpen ? styles.open : ''}`}>▼</span>
            </button>
            {isOpen && (
                <div className={styles.accordionContent}>
                    <textarea
                        className={styles.editTextarea}
                        value={content}
                        onChange={(e) => onContentChange(e.target.value)}
                        placeholder={`Enter details for "${title}" here...`}
                    />
                </div>
            )}
        </div>
    );
};

const ReviewModal = ({ reportData, departmentName, onClose, onConfirm }) => {
    const reportPreviewRef = useRef();
    const sectionTitles = Object.keys(reportData);

    const handleGeneratePdf = () => {
        const pdf = new jsPDF('p', 'mm', 'a4');
        const element = reportPreviewRef.current;

        const scaleFactor = 0.24;

        const pagePadding = 7; 
        const contentWidthMM = 210 - (2 * pagePadding); 

        pdf.html(element, {
            callback: function (pdf) {
                pdf.save(`${departmentName}-Annual-Report.pdf`);
                onConfirm();
            },
            x: pagePadding,
            y: pagePadding,
            width: contentWidthMM,
            windowWidth: element.offsetWidth,

            html2canvas: {
                scale: scaleFactor, 
                useCORS: true
            }
        });
    };

    return (
        <div className={styles.modalOverlay}>
            <div className={styles.modalContainer}>
                <div className={styles.modalContent} ref={reportPreviewRef}>
                    <div className={styles.pdfHeader}>
                        <img
                            src="/header.jpg" 
                            alt="Institution Logo"
                            className={styles.headerLogo}
                            crossOrigin="anonymous"
                        />
                    </div>

                    <h2 className={styles.modalTitle}>Annual Report</h2>
                    <h3 className={styles.modalSubtitle}>{departmentName}</h3>

                    <p className={styles.reportDate}>
                        Date of Report: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
                    </p>

                    {sectionTitles.map((title, index) => (
                        <React.Fragment key={title}>
                            <div className={styles.reviewSection}>
                                <h4>{title}</h4>
                                <p className={styles.reportContentText}>{reportData[title] || "No content provided for this section."}</p>
                            </div>

                            {index < sectionTitles.length - 1 && (
                                <hr className={styles.sectionSeparator} />
                            )}
                        </React.Fragment>
                    ))}

                    <div className={styles.pdfFooter}>
                        <p>Page 1 of 1 | Generated by Report System</p>
                    </div>

                </div>

                <div className={styles.modalActions}>
                    <button onClick={onClose} className={styles.secondaryButton}>Close</button>
                    <button onClick={handleGeneratePdf} className={styles.primaryButton}>Confirm & Generate PDF</button>
                </div>

            </div>
        </div>
    );
};


// --- Main Page Component (Unchanged) ---
const ReportStructurePageCSE = () => {
    const departmentName = "Computer Science & Engineering";
    const [reportData, setReportData] = useState({
        "1. Vision and Mission":
            "Department Vision:\n\"To create professionally competent and socially responsible technocrats with latest knowledge and innovative ideas to uplift the academy, industry and society.\"\n\nDepartment Mission:\n- To achieve academic excellence by imparting in-depth knowledge to the students through effective pedagogies and practical exposure on latest tools and technologies.\n- To provide environment & opportunity for students to bring out their inherent talents for their overall development through various programs, workshops, training and seminars.\n- To promote innovative research in Computer Science and Engineering and Interdisciplinary domains to cater the needs of the Government, Industry and Society.\n- To Educate and nurture entrepreneurial and ethical values through guidance and support.",
        "2. Faculty and Staff Details": "",
        "3. Student Achievements": "",
        "4. Research and Publications": "",
        "5. Labs and Infrastructure": "",
        "6. Events and Activities": "",
        "7. Budget and Utilization": ""
    });
    const [isReviewing, setIsReviewing] = useState(false);

    const handleSectionChange = (sectionTitle, newContent) => {
        setReportData(prevData => ({ ...prevData, [sectionTitle]: newContent }));
    };

    const handleFinalSubmit = () => {
        console.log("Submitting final report data to the backend...", reportData);
        setIsReviewing(false);
    };

    return (
        <div className={styles.pageContainer}>
            {isReviewing && (
                <ReviewModal
                    reportData={reportData}
                    departmentName={departmentName}
                    onClose={() => setIsReviewing(false)}
                    onConfirm={handleFinalSubmit}
                />
            )}

            <header className={styles.header}>
                <div className={styles.breadcrumbs}>Reports / <strong>{departmentName}</strong></div>
                <h1 className={styles.title}>Annual Report Editor</h1>
                <p className={styles.subtitle}>Fill out each section to complete the report.</p>
            </header>

            <div className={styles.accordion}>
                {Object.keys(reportData).map((sectionTitle) => (
                    <AccordionItem
                        key={sectionTitle}
                        title={sectionTitle}
                        content={reportData[sectionTitle]}
                        onContentChange={(newContent) => handleSectionChange(sectionTitle, newContent)}
                    />
                ))}
            </div>

            <div className={styles.actionButtons}>
                <button className={styles.secondaryButton}>Save as Draft</button>
                <button className={styles.primaryButton} onClick={() => setIsReviewing(true)}>
                    Review & Submit Report
                </button>
            </div>
        </div>
    );
};

export default ReportStructurePageCSE;